# SwiftLint Configuration for HomeMaint Mobile

# Paths to exclude from linting
excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - HomeMaintMobileTests/Mocks  # Allow more flexibility in test mocks

# Opt-in rules (not enabled by default)
opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_first_last
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_string
  - fallthrough
  - fatal_error_message
  - force_unwrapping  # Enforce safe unwrapping
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_whitespace  # Let formatter handle this

# Rule customization
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id  # Common in database models
    - db  # Database references
    - vm  # ViewModel abbreviation

# Force unwrapping configuration
force_unwrapping:
  severity: error  # Treat force unwrapping as error

# Type name configuration
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

# Custom rules
custom_rules:
  no_print:
    name: "No print statements"
    regex: "print\\("
    message: "Use proper logging (os_log) instead of print"
    severity: warning

  no_force_try:
    name: "No force try"
    regex: "try!"
    message: "Use proper error handling instead of try!"
    severity: error
